# Generated by Django 5.0.1 on 2024-03-07 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cwr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cwr_part_number",
                    models.CharField(
                        blank=True,
                        db_column="CWR Part Number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "manufacturer_part_number",
                    models.CharField(
                        blank=True,
                        db_column="Manufacturer Part Number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upc_code",
                    models.CharField(
                        blank=True, db_column="UPC Code", max_length=255, null=True
                    ),
                ),
                (
                    "quantity_available_to_ship_combined_field",
                    models.IntegerField(
                        blank=True,
                        db_column="Quantity Available to Ship (Combined)",
                        null=True,
                    ),
                ),
                (
                    "quantity_available_to_ship_nj_field",
                    models.IntegerField(
                        blank=True,
                        db_column="Quantity Available to Ship (NJ)",
                        null=True,
                    ),
                ),
                (
                    "quantity_available_to_ship_fl_field",
                    models.IntegerField(
                        blank=True,
                        db_column="Quantity Available to Ship (FL)",
                        null=True,
                    ),
                ),
                (
                    "next_shipment_date_combined_field",
                    models.DateField(
                        blank=True, db_column="Next Shipment Date (Combined)", null=True
                    ),
                ),
                (
                    "next_shipment_date_nj_field",
                    models.DateField(
                        blank=True, db_column="Next Shipment Date (NJ)", null=True
                    ),
                ),
                (
                    "next_shipment_date_fl_field",
                    models.DateField(
                        blank=True, db_column="Next Shipment Date (FL)", null=True
                    ),
                ),
                (
                    "your_cost",
                    models.DecimalField(
                        blank=True,
                        db_column="Your Cost",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        db_column="List Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "m_a_p_price",
                    models.DecimalField(
                        blank=True,
                        db_column="M.A.P. Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "m_r_p_price",
                    models.DecimalField(
                        blank=True,
                        db_column="M.R.P. Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "uppercase_title",
                    models.CharField(
                        blank=True,
                        db_column="Uppercase Title",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=255, null=True
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        blank=True, db_column="Full Description", null=True
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(blank=True, db_column="Category ID", null=True),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True, db_column="Category Name", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(
                        blank=True,
                        db_column="Manufacturer Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping Weight",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "box_height",
                    models.DecimalField(
                        blank=True,
                        db_column="Box Height",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "box_length",
                    models.DecimalField(
                        blank=True,
                        db_column="Box Length",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "box_width",
                    models.DecimalField(
                        blank=True,
                        db_column="Box Width",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "list_of_accessories_by_sku",
                    models.TextField(
                        blank=True, db_column="List of Accessories by SKU", null=True
                    ),
                ),
                (
                    "list_of_accessories_by_mfg_field",
                    models.TextField(
                        blank=True, db_column="List of Accessories by MFG#", null=True
                    ),
                ),
                (
                    "quick_specs",
                    models.TextField(blank=True, db_column="Quick Specs", null=True),
                ),
                (
                    "image_300x300_url",
                    models.CharField(
                        blank=True,
                        db_column="Image (300x300) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image_1000x1000_url",
                    models.CharField(
                        blank=True,
                        db_column="Image (1000x1000) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "non_stock",
                    models.IntegerField(blank=True, db_column="Non-stock", null=True),
                ),
                (
                    "drop_ships_direct_from_vendor",
                    models.IntegerField(
                        blank=True, db_column="Drop Ships Direct From Vendor", null=True
                    ),
                ),
                (
                    "hazardous_materials",
                    models.IntegerField(
                        blank=True, db_column="Hazardous Materials", null=True
                    ),
                ),
                (
                    "truck_freight",
                    models.IntegerField(
                        blank=True, db_column="Truck Freight", null=True
                    ),
                ),
                (
                    "exportable",
                    models.IntegerField(blank=True, db_column="Exportable", null=True),
                ),
                (
                    "first_class_mail",
                    models.IntegerField(
                        blank=True, db_column="First Class Mail", null=True
                    ),
                ),
                (
                    "oversized",
                    models.IntegerField(blank=True, db_column="Oversized", null=True),
                ),
                (
                    "remanufactured",
                    models.IntegerField(
                        blank=True, db_column="Remanufactured", null=True
                    ),
                ),
                (
                    "closeout",
                    models.IntegerField(blank=True, db_column="Closeout", null=True),
                ),
                (
                    "harmonization_code",
                    models.CharField(
                        blank=True,
                        db_column="Harmonization Code",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True,
                        db_column="Country Of Origin",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("sale", models.IntegerField(blank=True, db_column="Sale", null=True)),
                (
                    "original_price_if_on_sale_closeout_field",
                    models.DecimalField(
                        blank=True,
                        db_column="Original Price (If on Sale/Closeout)",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sale_start_date",
                    models.DateField(
                        blank=True, db_column="Sale Start Date", null=True
                    ),
                ),
                (
                    "sale_end_date",
                    models.DateField(blank=True, db_column="Sale End Date", null=True),
                ),
                (
                    "rebate",
                    models.IntegerField(blank=True, db_column="Rebate", null=True),
                ),
                (
                    "rebate_description",
                    models.TextField(
                        blank=True, db_column="Rebate Description", null=True
                    ),
                ),
                (
                    "rebate_start_date",
                    models.DateField(
                        blank=True, db_column="Rebate Start Date", null=True
                    ),
                ),
                (
                    "rebate_end_date",
                    models.DateField(
                        blank=True, db_column="Rebate End Date", null=True
                    ),
                ),
                (
                    "google_merchant_category",
                    models.CharField(
                        blank=True,
                        db_column="Google Merchant Category",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "quick_guide_literature_pdf_url",
                    models.CharField(
                        blank=True,
                        db_column="Quick Guide Literature (pdf) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "owners_manual_pdf_url",
                    models.CharField(
                        blank=True,
                        db_column="Owners Manual (pdf) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "brochure_literature_pdf_url",
                    models.CharField(
                        blank=True,
                        db_column="Brochure Literature (pdf) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "installation_guide_pdf_url",
                    models.CharField(
                        blank=True,
                        db_column="Installation Guide (pdf) Url",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "video_urls",
                    models.TextField(blank=True, db_column="Video Urls", null=True),
                ),
                (
                    "prop_65",
                    models.IntegerField(blank=True, db_column="Prop 65", null=True),
                ),
                (
                    "prop_65_description",
                    models.TextField(
                        blank=True, db_column="Prop 65 Description", null=True
                    ),
                ),
                (
                    "free_shipping",
                    models.IntegerField(
                        blank=True, db_column="Free Shipping", null=True
                    ),
                ),
                (
                    "free_shipping_end_date",
                    models.DateField(
                        blank=True, db_column="Free Shipping End Date", null=True
                    ),
                ),
                (
                    "returnable",
                    models.IntegerField(blank=True, db_column="Returnable", null=True),
                ),
                (
                    "image_additional_1000x1000_urls",
                    models.TextField(
                        blank=True,
                        db_column="Image Additional (1000x1000) Urls",
                        null=True,
                    ),
                ),
                (
                    "case_qty_nj_field",
                    models.IntegerField(
                        blank=True, db_column="Case Qty (NJ)", null=True
                    ),
                ),
                (
                    "case_qty_fl_field",
                    models.IntegerField(
                        blank=True, db_column="Case Qty (FL)", null=True
                    ),
                ),
                (
                    "number_3rd_party_marketplaces",
                    models.TextField(
                        blank=True, db_column="3rd Party Marketplaces", null=True
                    ),
                ),
                (
                    "fcc_id",
                    models.CharField(
                        blank=True, db_column="FCC ID", max_length=255, null=True
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("mfgn", models.CharField(blank=True, max_length=255, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                ("qtynj", models.IntegerField(blank=True, null=True)),
                ("qtyfl", models.IntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "map",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fragrancex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        blank=True, db_column="ITEM", max_length=255, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="NAME", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="DESCRIPTION", null=True),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_column="BRAND", max_length=255, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="TITLE", max_length=255, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="GENDER", max_length=255, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="SIZE", max_length=255, null=True
                    ),
                ),
                (
                    "metric_size",
                    models.CharField(
                        blank=True, db_column="METRIC_SIZE", max_length=255, null=True
                    ),
                ),
                (
                    "retail",
                    models.CharField(
                        blank=True, db_column="RETAIL", max_length=255, null=True
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, db_column="PRICE", max_length=255, null=True
                    ),
                ),
                (
                    "eur_price",
                    models.CharField(
                        blank=True, db_column="EUR_PRICE", max_length=255, null=True
                    ),
                ),
                (
                    "gbp_price",
                    models.CharField(
                        blank=True, db_column="GBP_PRICE", max_length=255, null=True
                    ),
                ),
                (
                    "cad_price",
                    models.CharField(
                        blank=True, db_column="CAD_PRICE", max_length=255, null=True
                    ),
                ),
                (
                    "aud_price",
                    models.CharField(
                        blank=True, db_column="AUD_PRICE", max_length=255, null=True
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, db_column="IMAGE", max_length=255, null=True
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="URL", max_length=255, null=True
                    ),
                ),
                (
                    "qty",
                    models.CharField(
                        blank=True, db_column="QTY", max_length=255, null=True
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, db_column="UPC", max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralProducttable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_column="SKU", max_length=255, null=True
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_column="Quantity", null=True),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, db_column="UPC", max_length=255, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=255, null=True
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        blank=True, db_column="Detailed_Description", null=True
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, db_column="Image", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_column="Category", max_length=255, null=True
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(blank=True, db_column="Category_ID", null=True),
                ),
                (
                    "msrp",
                    models.DecimalField(
                        blank=True,
                        db_column="MSRP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, db_column="MPN", max_length=255, null=True
                    ),
                ),
                (
                    "map",
                    models.DecimalField(
                        blank=True,
                        db_column="MAP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensionh",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionH",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensionl",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionL",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensionw",
                    models.DecimalField(
                        blank=True,
                        db_column="DimensionW",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Weight",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_length",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Length",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_width",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Width",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_height",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Height",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "attribute_1",
                    models.CharField(
                        blank=True, db_column="Attribute_1", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_2",
                    models.CharField(
                        blank=True, db_column="Attribute_2", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_3",
                    models.CharField(
                        blank=True, db_column="Attribute_3", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_4",
                    models.CharField(
                        blank=True, db_column="Attribute_4", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_5",
                    models.CharField(
                        blank=True, db_column="Attribute_5", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_6",
                    models.CharField(
                        blank=True, db_column="Attribute_6", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_7",
                    models.CharField(
                        blank=True, db_column="Attribute_7", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_8",
                    models.CharField(
                        blank=True, db_column="Attribute_8", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_9",
                    models.CharField(
                        blank=True, db_column="Attribute_9", max_length=255, null=True
                    ),
                ),
                (
                    "attribute_10",
                    models.CharField(
                        blank=True, db_column="Attribute_10", max_length=255, null=True
                    ),
                ),
                (
                    "feature_1",
                    models.TextField(blank=True, db_column="Feature_1", null=True),
                ),
                (
                    "feature_2",
                    models.TextField(blank=True, db_column="Feature_2", null=True),
                ),
                (
                    "feature_3",
                    models.TextField(blank=True, db_column="Feature_3", null=True),
                ),
                (
                    "feature_4",
                    models.TextField(blank=True, db_column="Feature_4", null=True),
                ),
                (
                    "feature_5",
                    models.TextField(blank=True, db_column="Feature_5", null=True),
                ),
                (
                    "feature_6",
                    models.TextField(blank=True, db_column="Feature_6", null=True),
                ),
                (
                    "feature_7",
                    models.TextField(blank=True, db_column="Feature_7", null=True),
                ),
                (
                    "feature_8",
                    models.TextField(blank=True, db_column="Feature_8", null=True),
                ),
                (
                    "feature_9",
                    models.TextField(blank=True, db_column="Feature_9", null=True),
                ),
                (
                    "feature_10",
                    models.TextField(blank=True, db_column="Feature_10", null=True),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="Model", max_length=255, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_column="Brand", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="Manufacturer", max_length=255, null=True
                    ),
                ),
                (
                    "prop_65",
                    models.IntegerField(blank=True, db_column="Prop_65", null=True),
                ),
                (
                    "prop_65_description",
                    models.TextField(
                        blank=True, db_column="Prop_65_Description", null=True
                    ),
                ),
                (
                    "manufacturer_id",
                    models.IntegerField(
                        blank=True, db_column="Manufacturer_Id", null=True
                    ),
                ),
                (
                    "date_created",
                    models.DateField(blank=True, db_column="Date_Created", null=True),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True, db_column="Thumbnail", max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lipsey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemnumber",
                    models.TextField(blank=True, db_column="ItemNumber", null=True),
                ),
                (
                    "description1",
                    models.TextField(blank=True, db_column="Description1", null=True),
                ),
                (
                    "description2",
                    models.TextField(blank=True, db_column="Description2", null=True),
                ),
                ("upc", models.TextField(blank=True, db_column="Upc", null=True)),
                (
                    "manufacturermodelno",
                    models.TextField(
                        blank=True, db_column="ManufacturerModelNo", null=True
                    ),
                ),
                ("msrp", models.TextField(blank=True, db_column="Msrp", null=True)),
                ("model", models.TextField(blank=True, db_column="Model", null=True)),
                (
                    "calibergauge",
                    models.TextField(blank=True, db_column="CaliberGauge", null=True),
                ),
                (
                    "manufacturer",
                    models.TextField(blank=True, db_column="Manufacturer", null=True),
                ),
                ("type", models.TextField(blank=True, db_column="Type", null=True)),
                ("action", models.TextField(blank=True, db_column="Action", null=True)),
                (
                    "barrellength",
                    models.TextField(blank=True, db_column="BarrelLength", null=True),
                ),
                (
                    "capacity",
                    models.TextField(blank=True, db_column="Capacity", null=True),
                ),
                ("finish", models.TextField(blank=True, db_column="Finish", null=True)),
                (
                    "overalllength",
                    models.TextField(blank=True, db_column="OverallLength", null=True),
                ),
                (
                    "receiver",
                    models.TextField(blank=True, db_column="Receiver", null=True),
                ),
                ("safety", models.TextField(blank=True, db_column="Safety", null=True)),
                ("sights", models.TextField(blank=True, db_column="Sights", null=True)),
                (
                    "stockframegrips",
                    models.TextField(
                        blank=True, db_column="StockFrameGrips", null=True
                    ),
                ),
                (
                    "magazine",
                    models.TextField(blank=True, db_column="Magazine", null=True),
                ),
                ("weight", models.TextField(blank=True, db_column="Weight", null=True)),
                (
                    "imagename",
                    models.TextField(blank=True, db_column="ImageName", null=True),
                ),
                (
                    "chamber",
                    models.TextField(blank=True, db_column="Chamber", null=True),
                ),
                (
                    "drilledandtapped",
                    models.TextField(
                        blank=True, db_column="DrilledAndTapped", null=True
                    ),
                ),
                (
                    "rateoftwist",
                    models.TextField(blank=True, db_column="RateOfTwist", null=True),
                ),
                (
                    "itemtype",
                    models.TextField(blank=True, db_column="ItemType", null=True),
                ),
                (
                    "additionalfeature1",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature1", null=True
                    ),
                ),
                (
                    "additionalfeature2",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature2", null=True
                    ),
                ),
                (
                    "additionalfeature3",
                    models.TextField(
                        blank=True, db_column="AdditionalFeature3", null=True
                    ),
                ),
                (
                    "shippingweight",
                    models.TextField(blank=True, db_column="ShippingWeight", null=True),
                ),
                (
                    "boundbookmanufacturer",
                    models.TextField(
                        blank=True, db_column="BoundBookManufacturer", null=True
                    ),
                ),
                (
                    "boundbookmodel",
                    models.TextField(blank=True, db_column="BoundBookModel", null=True),
                ),
                (
                    "boundbooktype",
                    models.TextField(blank=True, db_column="BoundBookType", null=True),
                ),
                (
                    "nfathreadpattern",
                    models.TextField(
                        blank=True, db_column="NfaThreadPattern", null=True
                    ),
                ),
                (
                    "nfaattachmentmethod",
                    models.TextField(
                        blank=True, db_column="NfaAttachmentMethod", null=True
                    ),
                ),
                (
                    "nfabaffletype",
                    models.TextField(blank=True, db_column="NfaBaffleType", null=True),
                ),
                (
                    "silencercanbedisassembled",
                    models.TextField(
                        blank=True, db_column="SilencerCanBeDisassembled", null=True
                    ),
                ),
                (
                    "silencerconstructionmaterial",
                    models.TextField(
                        blank=True, db_column="SilencerConstructionMaterial", null=True
                    ),
                ),
                (
                    "nfadbreduction",
                    models.TextField(blank=True, db_column="NfaDbReduction", null=True),
                ),
                (
                    "silenceroutsidediameter",
                    models.TextField(
                        blank=True, db_column="SilencerOutsideDiameter", null=True
                    ),
                ),
                (
                    "nfaform3caliber",
                    models.TextField(
                        blank=True, db_column="NfaForm3Caliber", null=True
                    ),
                ),
                (
                    "opticmagnification",
                    models.TextField(
                        blank=True, db_column="OpticMagnification", null=True
                    ),
                ),
                (
                    "maintubesize",
                    models.TextField(blank=True, db_column="MaintubeSize", null=True),
                ),
                (
                    "adjustableobjective",
                    models.TextField(
                        blank=True, db_column="AdjustableObjective", null=True
                    ),
                ),
                (
                    "objectivesize",
                    models.TextField(blank=True, db_column="ObjectiveSize", null=True),
                ),
                (
                    "opticadjustments",
                    models.TextField(
                        blank=True, db_column="OpticAdjustments", null=True
                    ),
                ),
                (
                    "illuminatedreticle",
                    models.TextField(
                        blank=True, db_column="IlluminatedReticle", null=True
                    ),
                ),
                (
                    "reticle",
                    models.TextField(blank=True, db_column="Reticle", null=True),
                ),
                (
                    "exclusive",
                    models.TextField(blank=True, db_column="Exclusive", null=True),
                ),
                (
                    "quantity",
                    models.TextField(blank=True, db_column="Quantity", null=True),
                ),
                (
                    "allocated",
                    models.TextField(blank=True, db_column="Allocated", null=True),
                ),
                ("onsale", models.TextField(blank=True, db_column="OnSale", null=True)),
                ("price", models.TextField(blank=True, db_column="Price", null=True)),
                (
                    "currentprice",
                    models.TextField(blank=True, db_column="CurrentPrice", null=True),
                ),
                (
                    "retailmap",
                    models.TextField(blank=True, db_column="RetailMap", null=True),
                ),
                (
                    "fflrequired",
                    models.TextField(blank=True, db_column="FflRequired", null=True),
                ),
                (
                    "sotrequired",
                    models.TextField(blank=True, db_column="SotRequired", null=True),
                ),
                (
                    "exclusivetype",
                    models.TextField(blank=True, db_column="ExclusiveType", null=True),
                ),
                (
                    "scopecoverincluded",
                    models.TextField(
                        blank=True, db_column="ScopeCoverIncluded", null=True
                    ),
                ),
                (
                    "special",
                    models.TextField(blank=True, db_column="Special", null=True),
                ),
                (
                    "sightstype",
                    models.TextField(blank=True, db_column="SightsType", null=True),
                ),
                ("case", models.TextField(blank=True, db_column="Case", null=True)),
                ("choke", models.TextField(blank=True, db_column="Choke", null=True)),
                (
                    "dbreduction",
                    models.TextField(blank=True, db_column="DbReduction", null=True),
                ),
                ("family", models.TextField(blank=True, db_column="Family", null=True)),
                (
                    "finishtype",
                    models.TextField(blank=True, db_column="FinishType", null=True),
                ),
                ("frame", models.TextField(blank=True, db_column="Frame", null=True)),
                (
                    "griptype",
                    models.TextField(blank=True, db_column="GripType", null=True),
                ),
                (
                    "handgunslidematerial",
                    models.TextField(
                        blank=True, db_column="HandgunSlideMaterial", null=True
                    ),
                ),
                (
                    "countryoforigin",
                    models.TextField(
                        blank=True, db_column="CountryOfOrigin", null=True
                    ),
                ),
                (
                    "itemlength",
                    models.TextField(blank=True, db_column="ItemLength", null=True),
                ),
                (
                    "itemwidth",
                    models.TextField(blank=True, db_column="ItemWidth", null=True),
                ),
                (
                    "itemheight",
                    models.TextField(blank=True, db_column="ItemHeight", null=True),
                ),
                (
                    "packagelength",
                    models.TextField(blank=True, db_column="PackageLength", null=True),
                ),
                (
                    "packagewidth",
                    models.TextField(blank=True, db_column="PackageWidth", null=True),
                ),
                (
                    "packageheight",
                    models.TextField(blank=True, db_column="PackageHeight", null=True),
                ),
                (
                    "itemgroup",
                    models.TextField(blank=True, db_column="ItemGroup", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rsr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rsr_stock_number",
                    models.CharField(
                        blank=True,
                        db_column="RSR_Stock_Number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, db_column="UPC", max_length=255, null=True
                    ),
                ),
                (
                    "dept_number",
                    models.CharField(
                        blank=True, db_column="Dept_Number", max_length=255, null=True
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True,
                        db_column="Retail_Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rsr_regular_price",
                    models.DecimalField(
                        blank=True,
                        db_column="RSR_Regular_Price",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "product_weight_oz",
                    models.DecimalField(
                        blank=True,
                        db_column="Product_Weight_oz",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "inventory_quantity",
                    models.IntegerField(
                        blank=True, db_column="Inventory_Quantity", null=True
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_column="Model", max_length=255, null=True
                    ),
                ),
                (
                    "full_manufacturer_name",
                    models.CharField(
                        blank=True,
                        db_column="Full_Manufacturer_Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image_name",
                    models.CharField(
                        blank=True, db_column="Image_Name", max_length=255, null=True
                    ),
                ),
                (
                    "ground_shipments_only",
                    models.CharField(
                        blank=True,
                        db_column="Ground_Shipments_Only",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "adult_sig_required",
                    models.CharField(
                        blank=True,
                        db_column="Adult_Sig_Required",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "blocked_from_dropship",
                    models.CharField(
                        blank=True,
                        db_column="Blocked_from_Dropship",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "retail_map",
                    models.DecimalField(
                        blank=True,
                        db_column="Retail_MAP",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_length_inches",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Length_inches",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_width_inches",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Width_inches",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_height_inches",
                    models.DecimalField(
                        blank=True,
                        db_column="Shipping_Height_inches",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "reserved_for_future_use",
                    models.CharField(
                        blank=True,
                        db_column="Reserved_for_Future_Use",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_column="Quantity", null=True),
                ),
                (
                    "manufacturer_id",
                    models.CharField(
                        blank=True,
                        db_column="Manufacturer_id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accessories",
                    models.TextField(blank=True, db_column="Accessories", null=True),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, db_column="Action", max_length=255, null=True
                    ),
                ),
                (
                    "type_of_barrel",
                    models.CharField(
                        blank=True,
                        db_column="Type_of_Barrel",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "barrel_length",
                    models.CharField(
                        blank=True, db_column="Barrel_Length", max_length=255, null=True
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        blank=True, db_column="Chamber", max_length=255, null=True
                    ),
                ),
                (
                    "chokes",
                    models.CharField(
                        blank=True, db_column="Chokes", max_length=255, null=True
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, db_column="Condition", max_length=255, null=True
                    ),
                ),
                (
                    "capacity",
                    models.TextField(blank=True, db_column="Capacity", null=True),
                ),
                (
                    "dram",
                    models.CharField(
                        blank=True, db_column="Dram", max_length=255, null=True
                    ),
                ),
                (
                    "edge",
                    models.CharField(
                        blank=True, db_column="Edge", max_length=255, null=True
                    ),
                ),
                (
                    "firing_casing",
                    models.CharField(
                        blank=True, db_column="Firing_casing", max_length=255, null=True
                    ),
                ),
                (
                    "finish",
                    models.CharField(
                        blank=True, db_column="Finish", max_length=255, null=True
                    ),
                ),
                (
                    "fit",
                    models.CharField(
                        blank=True, db_column="Fit", max_length=255, null=True
                    ),
                ),
                (
                    "feet_per_second",
                    models.CharField(
                        blank=True,
                        db_column="Feet_per_second",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "frame",
                    models.CharField(
                        blank=True, db_column="Frame", max_length=255, null=True
                    ),
                ),
                (
                    "caliber",
                    models.CharField(
                        blank=True, db_column="Caliber", max_length=255, null=True
                    ),
                ),
                (
                    "grain_weight",
                    models.CharField(
                        blank=True, db_column="Grain_Weight", max_length=255, null=True
                    ),
                ),
                (
                    "grips",
                    models.CharField(
                        blank=True, db_column="Grips", max_length=255, null=True
                    ),
                ),
                (
                    "hand",
                    models.CharField(
                        blank=True, db_column="Hand", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="Manufacturer", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer_part_number",
                    models.CharField(
                        blank=True,
                        db_column="Manufacturer_part_number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "manufacturer_weight",
                    models.CharField(
                        blank=True,
                        db_column="Manufacturer_weight",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "moa",
                    models.CharField(
                        blank=True, db_column="MOA", max_length=255, null=True
                    ),
                ),
                (
                    "nsn_national_stock_number",
                    models.CharField(
                        blank=True,
                        db_column="NSN_National_Stock_Number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "objective",
                    models.CharField(
                        blank=True, db_column="Objective", max_length=255, null=True
                    ),
                ),
                (
                    "ounce_of_shot",
                    models.CharField(
                        blank=True, db_column="Ounce_of_shot", max_length=255, null=True
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        blank=True, db_column="Packaging", max_length=255, null=True
                    ),
                ),
                (
                    "power",
                    models.CharField(
                        blank=True, db_column="Power", max_length=255, null=True
                    ),
                ),
                (
                    "reticle",
                    models.CharField(
                        blank=True, db_column="Reticle", max_length=255, null=True
                    ),
                ),
                (
                    "safety",
                    models.CharField(
                        blank=True, db_column="Safety", max_length=255, null=True
                    ),
                ),
                (
                    "sights",
                    models.CharField(
                        blank=True, db_column="Sights", max_length=255, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="Size", max_length=255, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="Type", max_length=255, null=True
                    ),
                ),
                (
                    "units_per_box",
                    models.CharField(
                        blank=True, db_column="Units_per_box", max_length=255, null=True
                    ),
                ),
                (
                    "units_per_case",
                    models.CharField(
                        blank=True,
                        db_column="Units_per_case",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wt_characteristics",
                    models.CharField(
                        blank=True,
                        db_column="Wt_Characteristics",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, db_column="Sub_Category", max_length=255, null=True
                    ),
                ),
                (
                    "diameter",
                    models.CharField(
                        blank=True, db_column="Diameter", max_length=255, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="Color", max_length=255, null=True
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, db_column="Material", max_length=255, null=True
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, db_column="Stock", max_length=255, null=True
                    ),
                ),
                (
                    "lens_color",
                    models.CharField(
                        blank=True, db_column="Lens_Color", max_length=255, null=True
                    ),
                ),
                (
                    "handle_color",
                    models.CharField(
                        blank=True, db_column="Handle_Color", max_length=255, null=True
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True, db_column="Category_Name", max_length=255, null=True
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True, db_column="Message_Type", max_length=255, null=True
                    ),
                ),
                (
                    "message_text",
                    models.TextField(blank=True, db_column="Message_Text", null=True),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, db_column="Municipality", max_length=255, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_column="State", max_length=255, null=True
                    ),
                ),
                (
                    "territory_restriction_type",
                    models.CharField(
                        blank=True,
                        db_column="Territory_Restriction_Type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "restriction_detail",
                    models.CharField(
                        blank=True,
                        db_column="Restriction_Detail",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description_deleted",
                    models.TextField(
                        blank=True, db_column="Description_Deleted", null=True
                    ),
                ),
                (
                    "sell_copy_description",
                    models.TextField(
                        blank=True, db_column="Sell_Copy_Description", null=True
                    ),
                ),
                (
                    "feature_1",
                    models.TextField(blank=True, db_column="Feature_1", null=True),
                ),
                (
                    "feature_2",
                    models.TextField(blank=True, db_column="Feature_2", null=True),
                ),
                (
                    "feature_3",
                    models.TextField(blank=True, db_column="Feature_3", null=True),
                ),
                (
                    "feature_4",
                    models.TextField(blank=True, db_column="Feature_4", null=True),
                ),
                (
                    "feature_5",
                    models.TextField(blank=True, db_column="Feature_5", null=True),
                ),
                (
                    "feature_6",
                    models.TextField(blank=True, db_column="Feature_6", null=True),
                ),
                (
                    "feature_7",
                    models.TextField(blank=True, db_column="Feature_7", null=True),
                ),
                (
                    "feature_8",
                    models.TextField(blank=True, db_column="Feature_8", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ssi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_column="SKU", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
                (
                    "datecreated",
                    models.CharField(
                        blank=True, db_column="DateCreated", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionh",
                    models.CharField(
                        blank=True, db_column="DimensionH", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionl",
                    models.CharField(
                        blank=True, db_column="DimensionL", max_length=255, null=True
                    ),
                ),
                (
                    "dimensionw",
                    models.CharField(
                        blank=True, db_column="DimensionW", max_length=255, null=True
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, db_column="Manufacturer", max_length=255, null=True
                    ),
                ),
                (
                    "imageurl",
                    models.CharField(
                        blank=True, db_column="ImageURL", max_length=255, null=True
                    ),
                ),
                (
                    "thumbnailurl",
                    models.CharField(
                        blank=True, db_column="ThumbnailURL", max_length=255, null=True
                    ),
                ),
                (
                    "upccode",
                    models.CharField(
                        blank=True, db_column="UPCCode", max_length=255, null=True
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, db_column="Weight", max_length=255, null=True
                    ),
                ),
                (
                    "weightunits",
                    models.CharField(
                        blank=True, db_column="WeightUnits", max_length=255, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_column="Category", max_length=255, null=True
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, db_column="Subcategory", max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=255, null=True
                    ),
                ),
                (
                    "map",
                    models.CharField(
                        blank=True, db_column="MAP", max_length=255, null=True
                    ),
                ),
                (
                    "msrp",
                    models.CharField(
                        blank=True, db_column="MSRP", max_length=255, null=True
                    ),
                ),
                (
                    "mpn",
                    models.CharField(
                        blank=True, db_column="MPN", max_length=255, null=True
                    ),
                ),
                (
                    "minimumorderquantity",
                    models.CharField(
                        blank=True,
                        db_column="MinimumOrderQuantity",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "detaileddescription",
                    models.CharField(
                        blank=True,
                        db_column="DetailedDescription",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shippingweight",
                    models.CharField(
                        blank=True,
                        db_column="ShippingWeight",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shippinglength",
                    models.CharField(
                        blank=True,
                        db_column="ShippingLength",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shippingwidth",
                    models.CharField(
                        blank=True, db_column="ShippingWidth", max_length=255, null=True
                    ),
                ),
                (
                    "shippingheight",
                    models.CharField(
                        blank=True,
                        db_column="ShippingHeight",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "attribute1",
                    models.CharField(
                        blank=True, db_column="Attribute1", max_length=255, null=True
                    ),
                ),
                (
                    "attribute2",
                    models.CharField(
                        blank=True, db_column="Attribute2", max_length=255, null=True
                    ),
                ),
                (
                    "attribute3",
                    models.CharField(
                        blank=True, db_column="Attribute3", max_length=255, null=True
                    ),
                ),
                (
                    "attribute4",
                    models.CharField(
                        blank=True, db_column="Attribute4", max_length=255, null=True
                    ),
                ),
                (
                    "attribute5",
                    models.CharField(
                        blank=True, db_column="Attribute5", max_length=255, null=True
                    ),
                ),
                (
                    "attribute6",
                    models.CharField(
                        blank=True, db_column="Attribute6", max_length=255, null=True
                    ),
                ),
                (
                    "attribute7",
                    models.CharField(
                        blank=True, db_column="Attribute7", max_length=255, null=True
                    ),
                ),
                (
                    "prop65warning",
                    models.CharField(
                        blank=True, db_column="Prop65Warning", max_length=255, null=True
                    ),
                ),
                (
                    "prop65reason",
                    models.CharField(
                        blank=True, db_column="Prop65Reason", max_length=255, null=True
                    ),
                ),
                (
                    "countryoforigin",
                    models.CharField(
                        blank=True,
                        db_column="CountryOfOrigin",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "groundshippingrequired",
                    models.CharField(
                        blank=True,
                        db_column="GroundShippingRequired",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, db_column="Price", max_length=255, null=True
                    ),
                ),
                (
                    "avgshipcost",
                    models.CharField(
                        blank=True, db_column="AvgShipCost", max_length=255, null=True
                    ),
                ),
                (
                    "qty",
                    models.CharField(
                        blank=True, db_column="Qty", max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendoEnronment",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_name", models.CharField(max_length=30, unique=True)),
                ("address_street1", models.CharField(max_length=150)),
                ("address_street2", models.CharField(max_length=150, null=True)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "ftp_username",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("ftp_password", models.CharField(max_length=50, null=True)),
                ("ftp_url", models.CharField(max_length=255)),
                ("file_urls", models.TextField()),
                ("host", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zanders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("desc1", models.TextField(blank=True, null=True)),
                ("desc2", models.TextField(blank=True, null=True)),
                ("itemnumber", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mfgpnumber", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "msrp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("qty1", models.IntegerField(blank=True, null=True)),
                ("qty2", models.IntegerField(blank=True, null=True)),
                ("qty3", models.IntegerField(blank=True, null=True)),
                ("upc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("serialized", models.IntegerField(blank=True, null=True)),
                (
                    "mapprice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "second_itemnumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("second_available", models.IntegerField(blank=True, null=True)),
                (
                    "second_price1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "second_price2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "second_price3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("second_qty1", models.IntegerField(blank=True, null=True)),
                ("second_qty2", models.IntegerField(blank=True, null=True)),
                ("second_qty3", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
