# Generated by Django 5.0.1 on 2024-04-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0002_remove_cwr_user_remove_fragrancex_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendoenronment",
            name="has_cwr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="has_frangrancex",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="has_lipsey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="has_rsr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="has_ssi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="has_zanders",
            field=models.BooleanField(default=False),
        ),
    ]
