# Generated by Django 5.0.1 on 2024-04-09 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0003_vendoenronment_has_cwr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendoenronment",
            old_name="has_frangrancex",
            new_name="has_fragrancex",
        ),
    ]
