# Generated by Django 5.0.1 on 2024-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0004_rename_has_frangrancex_vendoenronment_has_fragrancex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cwr",
            old_name="list_of_accessories_by_mfg_field",
            new_name="list_of_accessories_by_mfg",
        ),
        migrations.RenameField(
            model_name="zanders",
            old_name="second_itemnumber",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="case_qty_fl_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="case_qty_nj_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="next_shipment_date_combined_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="next_shipment_date_fl_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="next_shipment_date_nj_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="original_price_if_on_sale_closeout_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="quantity_available_to_ship_combined_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="quantity_available_to_ship_fl_field",
        ),
        migrations.RemoveField(
            model_name="cwr",
            name="quantity_available_to_ship_nj_field",
        ),
        migrations.RemoveField(
            model_name="generalproducttable",
            name="user",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_available",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_price1",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_price2",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_price3",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_qty1",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_qty2",
        ),
        migrations.RemoveField(
            model_name="zanders",
            name="second_qty3",
        ),
        migrations.AddField(
            model_name="cwr",
            name="case_qty_fl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="case_qty_nj",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="next_shipment_date_combined",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="next_shipment_date_fl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="next_shipment_date_nj",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="original_price_if_on_sale_closeout",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="quantity_available_to_ship_combined",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="quantity_available_to_ship_fl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cwr",
            name="quantity_available_to_ship_nj",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="zanders",
            name="imagelink",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="box_height",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="box_length",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="box_width",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="category_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="category_name",
            field=models.TextField(blank=True, db_column="Category Name", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="closeout",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="cwr_part_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="drop_ships_direct_from_vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="exportable",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="first_class_mail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="free_shipping",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="free_shipping_end_date",
            field=models.CharField(
                blank=True,
                db_column="Free Shipping End Date",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="hazardous_materials",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="list_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="m_a_p_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="m_r_p_price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="manufacturer_part_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="map",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="mfgn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="mrp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="non_stock",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="oversized",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="prop_65",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="qty",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="qtyfl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="qtynj",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_end_date",
            field=models.CharField(
                blank=True, db_column="Rebate End Date", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_start_date",
            field=models.CharField(
                blank=True, db_column="Rebate Start Date", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="remanufactured",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="returnable",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_end_date",
            field=models.CharField(
                blank=True, db_column="Sale End Date", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_start_date",
            field=models.CharField(
                blank=True, db_column="Sale Start Date", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="shipping_weight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="title",
            field=models.TextField(blank=True, db_column="Title", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="truck_freight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="upc_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="uppercase_title",
            field=models.TextField(blank=True, db_column="Uppercase Title", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="your_cost",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fragrancex",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lipsey",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="attribute7",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="avgshipcost",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="countryoforigin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="detaileddescription",
            field=models.TextField(
                blank=True, db_column="DetailedDescription", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="groundshippingrequired",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="prop65reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ssi",
            name="prop65warning",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="available",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="itemnumber",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="mapprice",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="msrp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="price1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="price2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="price3",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="qty1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="qty2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="qty3",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="serialized",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="weight",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
