# Generated by Django 5.0.1 on 2024-04-30 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendorApp",
            "0005_rename_list_of_accessories_by_mfg_field_cwr_list_of_accessories_by_mfg_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_cwr",
        ),
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_fragrancex",
        ),
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_lipsey",
        ),
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_rsr",
        ),
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_ssi",
        ),
        migrations.RemoveField(
            model_name="vendoenronment",
            name="has_zanders",
        ),
        migrations.AddField(
            model_name="cwr",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fragrancex",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalproducttable",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lipsey",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rsr",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ssi",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="brand",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="fixed_markup",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="percentage_markup",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="product_category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="product_filter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="send_orders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="shipping_cost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="shipping_cost_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="stock_maximum",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="stock_minimum",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="update_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="update_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="zanders",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="zanders",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
