# Generated by Django 5.0.1 on 2024-05-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0006_remove_vendoenronment_has_cwr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendoenronment",
            name="manufacturer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="oversized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="returnable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="serialized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="third_party_marketplaces",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendoenronment",
            name="truck_freight",
            field=models.BooleanField(default=False),
        ),
    ]
