# Generated by Django 5.0.1 on 2024-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendorApp",
            "0007_vendoenronment_manufacturer_vendoenronment_oversized_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="box_height",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="box_length",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="box_width",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="brochure_literature_pdf_url",
            field=models.TextField(
                blank=True, db_column="Brochure Literature (pdf) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="category_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="closeout",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="country_of_origin",
            field=models.TextField(
                blank=True, db_column="Country Of Origin", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="cwr_part_number",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="drop_ships_direct_from_vendor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="exportable",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="fcc_id",
            field=models.TextField(blank=True, db_column="FCC ID", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="first_class_mail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="free_shipping_end_date",
            field=models.TextField(
                blank=True, db_column="Free Shipping End Date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="google_merchant_category",
            field=models.TextField(
                blank=True, db_column="Google Merchant Category", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="harmonization_code",
            field=models.TextField(
                blank=True, db_column="Harmonization Code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="hazardous_materials",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="image_1000x1000_url",
            field=models.TextField(
                blank=True, db_column="Image (1000x1000) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="image_300x300_url",
            field=models.TextField(
                blank=True, db_column="Image (300x300) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="installation_guide_pdf_url",
            field=models.TextField(
                blank=True, db_column="Installation Guide (pdf) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="list_price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="m_a_p_price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="m_r_p_price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="manufacturer_name",
            field=models.TextField(
                blank=True, db_column="Manufacturer Name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="manufacturer_part_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="map",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="next_shipment_date_combined",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="next_shipment_date_fl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="next_shipment_date_nj",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="non_stock",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="original_price_if_on_sale_closeout",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="oversized",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="owners_manual_pdf_url",
            field=models.TextField(
                blank=True, db_column="Owners Manual (pdf) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="quantity_available_to_ship_fl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="quantity_available_to_ship_nj",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="quick_guide_literature_pdf_url",
            field=models.TextField(
                blank=True, db_column="Quick Guide Literature (pdf) Url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_end_date",
            field=models.TextField(blank=True, db_column="Rebate End Date", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_start_date",
            field=models.TextField(
                blank=True, db_column="Rebate Start Date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="remanufactured",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="returnable",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_end_date",
            field=models.TextField(blank=True, db_column="Sale End Date", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_start_date",
            field=models.TextField(blank=True, db_column="Sale Start Date", null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="shipping_weight",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sku",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="truck_freight",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="upc_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="your_cost",
            field=models.TextField(blank=True, null=True),
        ),
    ]
