# Generated by Django 5.0.1 on 2024-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0008_alter_cwr_box_height_alter_cwr_box_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="brochure_literature_pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="country_of_origin",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="cwr_part_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="free_shipping_end_date",
            field=models.CharField(
                blank=True,
                db_column="Free Shipping End Date",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="google_merchant_category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="harmonization_code",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="installation_guide_pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="manufacturer_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="owners_manual_pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="quick_guide_literature_pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_end_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="rebate_start_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_end_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="sale_start_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="upc_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="dimensionh",
            field=models.DecimalField(
                blank=True,
                db_column="DimensionH",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="dimensionl",
            field=models.DecimalField(
                blank=True,
                db_column="DimensionL",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="dimensionw",
            field=models.DecimalField(
                blank=True,
                db_column="DimensionW",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="map",
            field=models.DecimalField(
                blank=True, db_column="MAP", decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="msrp",
            field=models.DecimalField(
                blank=True, db_column="MSRP", decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="price",
            field=models.DecimalField(
                blank=True,
                db_column="Price",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="shipping_height",
            field=models.TextField(blank=True, db_column="Shipping_Height", null=True),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="shipping_length",
            field=models.DecimalField(
                blank=True,
                db_column="Shipping_Length",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="shipping_weight",
            field=models.DecimalField(
                blank=True,
                db_column="Shipping_Weight",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalproducttable",
            name="shipping_width",
            field=models.DecimalField(
                blank=True,
                db_column="Shipping_Width",
                decimal_places=6,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="action",
            field=models.TextField(blank=True, db_column="Action", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="adult_sig_required",
            field=models.TextField(
                blank=True, db_column="Adult_Sig_Required", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="barrel_length",
            field=models.TextField(blank=True, db_column="Barrel_Length", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="blocked_from_dropship",
            field=models.TextField(
                blank=True, db_column="Blocked_from_Dropship", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="caliber",
            field=models.TextField(blank=True, db_column="Caliber", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="category_name",
            field=models.TextField(blank=True, db_column="Category_Name", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="chamber",
            field=models.TextField(blank=True, db_column="Chamber", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="chokes",
            field=models.TextField(blank=True, db_column="Chokes", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="color",
            field=models.TextField(blank=True, db_column="Color", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="condition",
            field=models.TextField(blank=True, db_column="Condition", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="dept_number",
            field=models.TextField(blank=True, db_column="Dept_Number", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="diameter",
            field=models.TextField(blank=True, db_column="Diameter", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="dram",
            field=models.TextField(blank=True, db_column="Dram", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="edge",
            field=models.TextField(blank=True, db_column="Edge", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="feet_per_second",
            field=models.TextField(blank=True, db_column="Feet_per_second", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="finish",
            field=models.TextField(blank=True, db_column="Finish", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="firing_casing",
            field=models.TextField(blank=True, db_column="Firing_casing", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="fit",
            field=models.TextField(blank=True, db_column="Fit", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="frame",
            field=models.TextField(blank=True, db_column="Frame", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="full_manufacturer_name",
            field=models.TextField(
                blank=True, db_column="Full_Manufacturer_Name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="grain_weight",
            field=models.TextField(blank=True, db_column="Grain_Weight", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="grips",
            field=models.TextField(blank=True, db_column="Grips", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="ground_shipments_only",
            field=models.TextField(
                blank=True, db_column="Ground_Shipments_Only", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="hand",
            field=models.TextField(blank=True, db_column="Hand", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="handle_color",
            field=models.TextField(blank=True, db_column="Handle_Color", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="image_name",
            field=models.TextField(blank=True, db_column="Image_Name", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="lens_color",
            field=models.TextField(blank=True, db_column="Lens_Color", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="manufacturer",
            field=models.TextField(blank=True, db_column="Manufacturer", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="manufacturer_id",
            field=models.TextField(blank=True, db_column="Manufacturer_id", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="manufacturer_part_number",
            field=models.TextField(
                blank=True, db_column="Manufacturer_part_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="manufacturer_weight",
            field=models.TextField(
                blank=True, db_column="Manufacturer_weight", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="material",
            field=models.TextField(blank=True, db_column="Material", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="message_type",
            field=models.TextField(blank=True, db_column="Message_Type", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="moa",
            field=models.TextField(blank=True, db_column="MOA", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="model",
            field=models.TextField(blank=True, db_column="Model", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="municipality",
            field=models.TextField(blank=True, db_column="Municipality", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="nsn_national_stock_number",
            field=models.TextField(
                blank=True, db_column="NSN_National_Stock_Number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="objective",
            field=models.TextField(blank=True, db_column="Objective", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="ounce_of_shot",
            field=models.TextField(blank=True, db_column="Ounce_of_shot", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="packaging",
            field=models.TextField(blank=True, db_column="Packaging", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="power",
            field=models.TextField(blank=True, db_column="Power", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="product_weight_oz",
            field=models.TextField(
                blank=True, db_column="Product_Weight_oz", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="reserved_for_future_use",
            field=models.TextField(
                blank=True, db_column="Reserved_for_Future_Use", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="restriction_detail",
            field=models.TextField(
                blank=True, db_column="Restriction_Detail", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="retail_map",
            field=models.TextField(blank=True, db_column="Retail_MAP", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="retail_price",
            field=models.TextField(blank=True, db_column="Retail_Price", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="reticle",
            field=models.TextField(blank=True, db_column="Reticle", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="rsr_regular_price",
            field=models.TextField(
                blank=True, db_column="RSR_Regular_Price", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="rsr_stock_number",
            field=models.TextField(blank=True, db_column="RSR_Stock_Number", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="safety",
            field=models.TextField(blank=True, db_column="Safety", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="shipping_height_inches",
            field=models.TextField(
                blank=True, db_column="Shipping_Height_inches", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="shipping_length_inches",
            field=models.TextField(
                blank=True, db_column="Shipping_Length_inches", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="shipping_width_inches",
            field=models.TextField(
                blank=True, db_column="Shipping_Width_inches", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="sights",
            field=models.TextField(blank=True, db_column="Sights", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="size",
            field=models.TextField(blank=True, db_column="Size", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="state",
            field=models.TextField(blank=True, db_column="State", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="stock",
            field=models.TextField(blank=True, db_column="Stock", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="sub_category",
            field=models.TextField(blank=True, db_column="Sub_Category", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="territory_restriction_type",
            field=models.TextField(
                blank=True, db_column="Territory_Restriction_Type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="type",
            field=models.TextField(blank=True, db_column="Type", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="type_of_barrel",
            field=models.TextField(blank=True, db_column="Type_of_Barrel", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="units_per_box",
            field=models.TextField(blank=True, db_column="Units_per_box", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="units_per_case",
            field=models.TextField(blank=True, db_column="Units_per_case", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="upc",
            field=models.TextField(blank=True, db_column="UPC", null=True),
        ),
        migrations.AlterField(
            model_name="rsr",
            name="wt_characteristics",
            field=models.TextField(
                blank=True, db_column="Wt_Characteristics", null=True
            ),
        ),
        migrations.AlterField(
            model_name="zanders",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
