# Generated by Django 5.0.1 on 2024-06-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0009_alter_cwr_brochure_literature_pdf_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="cwr_part_number",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="upc_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
