# Generated by Django 5.0.1 on 2024-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0010_alter_cwr_cwr_part_number_alter_cwr_upc_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="quantity_available_to_ship_combined",
            field=models.TextField(blank=True, null=True),
        ),
    ]
