# Generated by Django 5.0.1 on 2024-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0011_alter_cwr_quantity_available_to_ship_combined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="free_shipping_end_date",
            field=models.TextField(
                blank=True, db_column="Free Shipping End Date", null=True
            ),
        ),
    ]
