# Generated by Django 5.0.1 on 2024-06-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0012_alter_cwr_free_shipping_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="rebate",
            field=models.TextField(blank=True, db_column="Rebate", null=True),
        ),
    ]
