# Generated by Django 5.0.1 on 2024-06-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0013_alter_cwr_rebate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="country_of_origin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="harmonization_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
