# Generated by Django 5.0.1 on 2024-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0014_alter_cwr_country_of_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwr",
            name="number_3rd_party_marketplaces",
            field=models.BooleanField(
                blank=True, db_column="3rd Party Marketplaces", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="oversized",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="returnable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cwr",
            name="truck_freight",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
