# Generated by Django 5.0.1 on 2024-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0015_alter_cwr_number_3rd_party_marketplaces_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendoenronment",
            name="ftp_username",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vendoenronment",
            name="vendor_name",
            field=models.CharField(max_length=30),
        ),
    ]
