# Generated by Django 5.0.1 on 2024-06-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendorApp", "0016_alter_vendoenronment_ftp_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendoenronment",
            name="vendor_identifier",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
